

// groups
export const LOAD_GROUPS_SUCCESS = "LOAD_GROUPS_SUCCESS";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const UPDATE_GROUP_SUCCESS = "UPDATE_GROUP_SUCCESS";

export const LOAD_WEATHERS_SUCCESS = "LOAD_WEATHERS_SUCCESS";
export const CREATE_WEATHER_SUCCESS = "CREATE_WEATHER_SUCCESS";
export const UPDATE_WEATHER_SUCCESS = "UPDATE_WEATHER_SUCCESS";

export const LOAD_CARDS_SUCCESS = "LOAD_CARDS_SUCCESS";
export const CREATE_CARD_SUCCESS = "CREATE_CARD_SUCCESS";
export const UPDATE_CARD_SUCCESS = "UPDATE_CARD_SUCCESS";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const DELETE_COURSE_OPTIMISTIC = "DELETE_COURSE_OPTIMISTIC";
export const DELETE_WEATHER_OPTIMISTIC = "DELETE_WEATHER_OPTIMISTIC";
export const DELETE_CARD_OPTIMISTIC = "DELETE_CARD_OPTIMISTIC";
export const DELETE_GROUP_OPTIMISTIC = "DELETE_GROUP_OPTIMISTIC";